/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/policy-copilot/v1/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 首页工作台概览
         * @description 对应对接文档 §5.2。返回覆盖政策数、占位 KPI、重点政策列表等。`servedEnterpriseCount`、`matchAnalysisCount` 当前为占位值 0，前端按 `--` 或“统计建设中”展示。
         */
        get: operations["getDashboardSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policy-copilot/v1/enterprises/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 搜索企业
         * @description 对应对接文档 §10.1。按企业名称或统一社会信用代码检索，多候选时展示企业名称与信用代码让用户选择。
         */
        get: operations["searchEnterprises"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policy-copilot/v1/policies/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 搜索政策
         * @description 对应对接文档 §10.2。按政策名称或简称检索，支持中英文引号与常见标点差异。
         */
        get: operations["searchPolicies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policy-copilot/v1/projects/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 搜索项目
         * @description 对应对接文档 §10.3。在指定政策范围内按项目名称检索；`policyQuery` 可选，缺省时在当前纳入匹配的全部政策内检索。
         */
        get: operations["searchProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policy-copilot/v1/matches/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 解析匹配对象
         * @description 对应对接文档 §10.4。可传 `query/enterpriseQuery/policyQuery/projectQuery`。多条结果时按企业、政策和项目名称让用户选择，不要求用户输入内部标识。
         */
        get: operations["resolveMatches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policy-copilot/v1/enterprises/{entUid}/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 企业政策画像
         * @description 对应对接文档 §7.3。路径变量为 `entUid`（对接文档称 `enterpriseId`）。前端优先使用 `entName/creditCode/province/city/industryCategory/profileItems/missingDataItems/abnormalFields`；`serviceProfile/indicators/missingFields` 为内部字段，前端不直接渲染。
         */
        get: operations["getEnterpriseContext"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policy-copilot/v1/policies/{policyId}/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 政策详情与项目条件
         * @description 对应对接文档 §6.3。返回政策基础信息与 `projects[].conditions[]`。条件字段映射见 §6.3：`indicator` 为指标名称、`compare+fieldVal` 为条件内容、`conditionRole==='must'` 为必要、`sourceClause` 为原文依据。`fieldName/indicatorId/indicatorScore` 为内部字段，前端不展示。
         */
        get: operations["getPolicyContext"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policy-copilot/v1/matches/policies-by-enterprise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 企业找政策（实时匹配）
         * @description 对应对接文档 §7.4。以 `entUid` 或 `enterpriseId` 为企业键实时计算并写入匹配结果。每条结果为“企业 + 政策 + 项目”，政策相同但项目不同必须保留为不同行。注意：DTO 中的 `matchLevels/policyAttribute/sort/pageNum/pageSize` 当前实时流程尚未实际应用，前端不得依赖其做服务端筛选与分页；前端按返回 `items[]` 自行聚合高中低数量。
         */
        post: operations["findPoliciesByEnterprise"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policy-copilot/v1/matches/enterprises-by-policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 政策找企业列表
         * @description 读取指定政策/项目的最新预计算匹配企业，支持匹配等级、企业名称关键词和分页。分页由后端 PageHelper 处理，返回 `total/pageNum/pageSize/pages/hasNext`。
         */
        post: operations["findEnterprisesByPolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policy-copilot/v1/matches/enterprises-by-policy/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 政策找企业统计
         * @description 统计指定政策/项目下最新预计算匹配结果的高、中、低匹配数量。该接口独立于列表分页，不接收 `pageNum/pageSize`。
         */
        get: operations["summarizeEnterprisesByPolicy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policy-copilot/v1/matches/{matchId}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 匹配条件证据
         * @description 对应对接文档 §6.5。按四态分组展示：`satisfied` 已满足、`unsatisfied` 明确不满足、`unknown` 待补充或待确认、`not_applicable` 不适用。禁止把 `unknown` 归入“不满足”。
         */
        get: operations["getMatchEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policy-copilot/v1/matches/{matchId}/gaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 匹配差距与材料提示
         * @description 对应对接文档 §6.5。`missingData` 为 `evidenceStatus=unknown` 的证据，`unsatisfied` 为 `unsatisfied` 的证据。`materials[]` 当前为通用提示，不是正式材料清单，页面标题应使用“材料准备提示”，不能标成“缺失材料明细”。
         */
        get: operations["getMatchGaps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policy-copilot/v1/ai-interactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 记录 AI 交互日志（补充接口）
         * @description 对接文档未将此接口列入前端必接范围，仅作为 AI 交互埋点补充。返回 `data` 为是否写入成功（布尔）。
         */
        post: operations["logAiInteraction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 统一响应包装。`code=200` 业务成功；`code=500` 业务失败（HTTP 仍为 200）。前端必须同时检查 HTTP 状态与 `body.code`。 */
        ApiResponseEnvelope: {
            /**
             * @description 200=成功，500=失败。
             * @example 200
             */
            code: number;
            /**
             * @description 提示信息；失败时为业务错误说明或错误码（如 `MATCH_NOT_FOUND`）。
             * @example 操作成功
             */
            msg: string;
            /** @description 业务数据，失败时为 null。 */
            data?: unknown;
        };
        DashboardSummaryResponse: components["schemas"]["ApiResponseEnvelope"] & {
            data?: components["schemas"]["DashboardSummary"];
        };
        /** @description 首页概览。 */
        DashboardSummary: {
            /** @example 1.0 */
            schemaVersion: string;
            kpis: components["schemas"]["DashboardKpis"];
            /** @description 今日快讯，当前为空数组；空时显示“暂无快讯”。 */
            news: {
                [key: string]: unknown;
            }[];
            /** @description 重点政策列表。 */
            topPolicies: components["schemas"]["TopPolicy"][];
            /** @description 重点企业列表，本期无数据，前端隐藏。 */
            topEnterprises: {
                [key: string]: unknown;
            }[];
        };
        DashboardKpis: {
            /**
             * @description 覆盖政策数（已完成）。
             * @example 7
             */
            activePolicyCount: number;
            /**
             * @description 已服务企业数，当前占位 0，前端显示 `--`。
             * @example 0
             */
            servedEnterpriseCount: number;
            /**
             * @description 累计匹配分析，当前占位 0，前端显示 `--`。
             * @example 0
             */
            matchAnalysisCount: number;
        };
        TopPolicy: {
            /**
             * Format: int64
             * @example 12
             */
            policyId: number;
            /** @example 节能改造补贴 */
            title: string;
            /**
             * @description 政策属性/支持方式。
             * @example 补贴
             */
            policyAttribute?: string | null;
            /**
             * Format: int64
             * @description 申报截止时间，epoch 毫秒。
             * @example 1718841600000
             */
            deadline?: number | null;
        };
        EnterpriseSearchResponse: components["schemas"]["ApiResponseEnvelope"] & {
            data?: components["schemas"]["EnterpriseSearch"];
        };
        EnterpriseSearch: {
            items: components["schemas"]["EnterpriseSearchItem"][];
        };
        EnterpriseSearchItem: {
            /** @description 企业标识（`entUid`）。 */
            enterpriseId: string;
            /** @description 企业名称。 */
            enterpriseName: string;
            /** @description 统一社会信用代码。 */
            creditCode?: string | null;
        };
        PolicySearchResponse: components["schemas"]["ApiResponseEnvelope"] & {
            data?: components["schemas"]["PolicySearch"];
        };
        PolicySearch: {
            items: components["schemas"]["PolicySearchItem"][];
        };
        PolicySearchItem: {
            /**
             * Format: int64
             * @example 12
             */
            policyId: number;
            /** @example 节能改造补贴 */
            policyName: string;
            /** @description 政策全称。 */
            policyFullName?: string | null;
        };
        ProjectSearchResponse: components["schemas"]["ApiResponseEnvelope"] & {
            data?: components["schemas"]["ProjectSearch"];
        };
        ProjectSearch: {
            items: components["schemas"]["ProjectSearchItem"][];
        };
        ProjectSearchItem: {
            /**
             * Format: int64
             * @example 12
             */
            policyId: number;
            /** @example 节能改造补贴 */
            policyName: string;
            /**
             * Format: int64
             * @example 4
             */
            projectId: number;
            /** @example 节能改造项目 */
            projectName: string;
        };
        MatchResolveResponse: components["schemas"]["ApiResponseEnvelope"] & {
            data?: components["schemas"]["MatchResolve"];
        };
        MatchResolve: {
            items: components["schemas"]["MatchResolveItem"][];
        };
        MatchResolveItem: {
            matchId: string;
            /** Format: int64 */
            policyId: number;
            policyName: string;
            /** Format: int64 */
            projectId?: number | null;
            projectName?: string | null;
            /** @description 企业标识（`entUid`）。 */
            enterpriseId: string;
            enterpriseName: string;
            /**
             * Format: double
             * @description 匹配分。
             */
            score?: number | null;
            /**
             * @description 匹配等级。
             * @enum {string|null}
             */
            matchLevel?: "high" | "medium" | "low" | "none" | null;
        };
        EnterprisePolicyContextResponse: components["schemas"]["ApiResponseEnvelope"] & {
            data?: components["schemas"]["EnterprisePolicyContext"];
        };
        /** @description 企业政策画像。 */
        EnterprisePolicyContext: {
            /** @example 1.0 */
            schemaVersion: string;
            /** @description 企业标识。 */
            entUid: string;
            /** @description 企业名称。 */
            entName: string;
            /** @description 统一社会信用代码。 */
            creditCode?: string | null;
            province?: string | null;
            city?: string | null;
            /** @description 行业。 */
            industryCategory?: string | null;
            /** @description 业务服务画像，内部字段，不是稳定前端契约，前端不直接渲染。 */
            serviceProfile?: {
                [key: string]: unknown;
            } | null;
            /** @description 内部指标值，前端不直接渲染。 */
            indicators?: components["schemas"]["EnterpriseIndicatorValue"][];
            /** @description 业务化画像项，前端展示业务名称、值、来源、更新时间。 */
            profileItems: components["schemas"]["ProfileItem"][];
            /** @description 内部缺失字段名列表，前端不直接渲染。 */
            missingFields: string[];
            /** @description 业务化缺失数据项，前端可展示。 */
            missingDataItems: string[];
            /** @description 异常字段。 */
            abnormalFields: string[];
        };
        ProfileItem: {
            /** @description 业务名称。 */
            name: string;
            /** @description 值。 */
            value?: string | null;
            /** @description 单位。 */
            unit?: string | null;
            /** @description 业务数据状态，如 已核验/已获取/待补充。 */
            status: string;
            /** @description 业务数据来源，如 工商登记信息/企业补充信息/待补充。 */
            source: string;
            /**
             * Format: int64
             * @description 更新时间，epoch 毫秒。
             */
            updatedAt?: number | null;
        };
        /** @description 企业指标值（内部字段，前端不直接渲染）。 */
        EnterpriseIndicatorValue: {
            /** @description 内部字段名。 */
            fieldName?: string;
            fieldValue?: string | null;
            /** @description 缺失时为 `unknown`。 */
            valueType?: string | null;
            unit?: string | null;
            /** @description 如 financial_ent_basic/policy_enterprise_indicator/missing/derived。 */
            sourceType?: string | null;
            sourceRef?: string | null;
            verifiedStatus?: string | null;
            /**
             * Format: int64
             * @description 更新时间，epoch 毫秒。
             */
            updatedAt?: number | null;
        };
        PolicyMatchContextResponse: components["schemas"]["ApiResponseEnvelope"] & {
            data?: components["schemas"]["PolicyMatchContext"];
        };
        /** @description 政策详情与项目条件。 */
        PolicyMatchContext: {
            /** @example 1.0 */
            schemaVersion: string;
            /**
             * Format: int64
             * @example 12
             */
            policyId: number;
            /** @example 节能改造补贴 */
            title: string;
            /** @description 政策全称。 */
            titleFull?: string | null;
            /** @description 发文文号。 */
            documentNo?: string | null;
            /** @description 发布单位。 */
            issuingOrg?: string | null;
            /** @description 地区。 */
            region?: string | null;
            /** @description 政策级别。 */
            level?: string | null;
            /** @description 政策属性/支持方式。 */
            policyAttribute?: string | null;
            /**
             * Format: int64
             * @description 申报截止时间，epoch 毫秒；前端可计算剩余天数。
             */
            deadline?: number | null;
            /** @description 申报材料（文本）。 */
            materials?: string | null;
            /** @description 办理流程（文本）。 */
            process?: string | null;
            projects: components["schemas"]["PolicyProjectItem"][];
        };
        PolicyProjectItem: {
            /**
             * Format: int64
             * @example 4
             */
            projectId: number;
            /** @example 节能改造项目 */
            projectName: string;
            /** @description 主体类型，如 enterprise。 */
            subjectType?: string | null;
            /** @description 条件分组关系，如 OR。 */
            groupsRelation?: string | null;
            conditions: components["schemas"]["PolicyConditionItem"][];
        };
        /** @description 申报条件。前端展示 `indicator`、`compare+fieldVal`、`conditionRole`、`sourceClause`；不展示 `fieldName/indicatorId/indicatorScore`。 */
        PolicyConditionItem: {
            /**
             * Format: int64
             * @description 内部标识，不展示。
             */
            indicatorId?: number | null;
            /** @description 指标名称（业务文案）。 */
            indicator: string;
            /** @description 内部字段名，不展示。 */
            fieldName?: string | null;
            /** @description 比较运算符，如 EQ/GTE 等。 */
            compare?: string | null;
            /** @description 条件值/阈值。 */
            fieldVal?: string | null;
            /**
             * @description 条件角色。
             * @enum {string|null}
             */
            conditionRole?: "must" | "optional" | null;
            /** @description 内部评分权重，不展示。 */
            indicatorScore?: number | null;
            /** @description 政策原文依据。 */
            sourceClause?: string | null;
            /**
             * @description 条件状态。
             * @enum {string|null}
             */
            matchStatus?: "enabled" | "manual_confirm" | "disabled" | null;
        };
        /** @description 企业找政策请求。仅 `entUid` 或 `enterpriseId` 为必填企业键；其余字段当前实时流程未实际应用。 */
        FindPoliciesForEnterpriseRequest: {
            /** @description 企业标识（与 `enterpriseId` 二选一）。 */
            entUid?: string | null;
            /** @description 企业标识（与 `entUid` 二选一）。 */
            enterpriseId?: string | null;
            entName?: string | null;
            creditCode?: string | null;
            /** @description 当前未应用。 */
            policyAttribute?: string | null;
            /** @description 当前未应用，前端按返回结果自行聚合。 */
            matchLevels?: ("high" | "medium" | "low" | "none")[] | null;
            /** @description 当前未应用。 */
            sort?: string | null;
            /** @description 当前未应用。 */
            pageNum?: number | null;
            /** @description 当前未应用。 */
            pageSize?: number | null;
        };
        /** @description 政策找企业请求。 */
        FindEnterprisesForPolicyRequest: {
            /**
             * Format: int64
             * @description 政策 ID（必填）。
             * @example 12
             */
            policyId: number;
            /**
             * Format: int64
             * @description 项目 ID；切换项目时传对应值，不限定传 null。
             * @example 4
             */
            projectId?: number | null;
            /** @description 企业名称关键词，服务端筛选。 */
            keyword?: string | null;
            /** @description 匹配等级筛选：high/medium/low，全部传三者。 */
            matchLevels?: ("high" | "medium" | "low" | "none")[] | null;
            /** @example 1 */
            pageNum?: number | null;
            /** @example 20 */
            pageSize?: number | null;
        };
        MatchListResponse: components["schemas"]["ApiResponseEnvelope"] & {
            data?: components["schemas"]["MatchList"];
        };
        /** @description 匹配结果列表。空结果时 `items=[]` 且 `message` 给出业务化空态文案。 */
        MatchList: {
            /** @example 1.0 */
            schemaVersion: string;
            /** @description 分析批次 ID（企业找政策返回）。 */
            analysisId?: string | null;
            items: components["schemas"]["MatchItem"][];
            /**
             * Format: int64
             * @description 政策找企业列表总记录数。
             */
            total: number;
            /** @description 当前页码。 */
            pageNum: number;
            /** @description 每页大小。 */
            pageSize: number;
            /** @description 总页数。 */
            pages: number;
            /** @description 是否还有下一页。 */
            hasNext: boolean;
            /** @description 空态业务文案。 */
            message?: string | null;
        };
        /** @description 一条“企业 + 政策 + 项目”匹配结果。注意：政策找企业接口返回时四态计数为 null、`mainEvidenceSummary` 为空数组；企业找政策接口返回时四态计数与主证据摘要有值。 */
        MatchItem: {
            /** @description 匹配结果标识。 */
            matchId: string;
            /** Format: int64 */
            policyId: number;
            /** Format: int64 */
            projectId: number;
            policyTitle: string;
            projectName: string;
            /** @description 企业标识。 */
            entUid: string;
            /** @description 企业名称（政策找企业返回，企业找政策可能为 null）。 */
            entName?: string | null;
            /**
             * Format: double
             * @description 匹配分。
             */
            score?: number | null;
            /**
             * @description 匹配等级。
             * @enum {string|null}
             */
            matchLevel?: "high" | "medium" | "low" | "none" | null;
            /**
             * @description 准入状态。
             * @enum {string|null}
             */
            eligibilityStatus?: "eligible" | "need_confirmation" | "not_eligible" | null;
            /**
             * Format: double
             * @description 置信度。
             */
            confidence?: number | null;
            /** @description 已满足条件数。 */
            satisfiedCount?: number | null;
            /** @description 明确不满足条件数。 */
            unsatisfiedCount?: number | null;
            /** @description 待补充或待确认条件数。 */
            unknownCount?: number | null;
            /** @description 不适用条件数。 */
            notApplicableCount?: number | null;
            /** @description 主证据摘要（前 5 条）。 */
            mainEvidenceSummary?: string[];
        };
        PolicyEnterpriseMatchSummaryResponse: components["schemas"]["ApiResponseEnvelope"] & {
            data?: components["schemas"]["PolicyEnterpriseMatchSummary"];
        };
        /** @description 政策找企业统计，不受列表分页影响。 */
        PolicyEnterpriseMatchSummary: {
            /** @example 1.0 */
            schemaVersion: string;
            /**
             * Format: int64
             * @example 100
             */
            total: number;
            /**
             * Format: int64
             * @example 20
             */
            highCount: number;
            /**
             * Format: int64
             * @example 50
             */
            mediumCount: number;
            /**
             * Format: int64
             * @example 30
             */
            lowCount: number;
        };
        MatchEvidenceResponse: components["schemas"]["ApiResponseEnvelope"] & {
            data?: components["schemas"]["MatchEvidence"];
        };
        MatchEvidence: {
            /** @example 1.0 */
            schemaVersion: string;
            matchId: string;
            items: components["schemas"]["PolicyMatchEvidence"][];
        };
        MatchGapsResponse: components["schemas"]["ApiResponseEnvelope"] & {
            data?: components["schemas"]["MatchGaps"];
        };
        MatchGaps: {
            /** @example 1.0 */
            schemaVersion: string;
            matchId: string;
            /** @description `evidenceStatus=unknown` 的证据。 */
            missingData: components["schemas"]["PolicyMatchEvidence"][];
            /** @description `evidenceStatus=unsatisfied` 的证据。 */
            unsatisfied: components["schemas"]["PolicyMatchEvidence"][];
            /** @description 材料准备提示（通用，非正式材料清单）。 */
            materials: string[];
        };
        /** @description 单条条件证据。前端按 `evidenceStatus` 分组；`fieldName/indicatorId` 为内部字段不展示。 */
        PolicyMatchEvidence: {
            /**
             * Format: int64
             * @description 内部主键。
             */
            id?: number | null;
            matchId?: string | null;
            /**
             * Format: int64
             * @description 内部标识，不展示。
             */
            indicatorId?: number | null;
            /**
             * @description 四态证据状态。
             * @enum {string}
             */
            evidenceStatus: "satisfied" | "unsatisfied" | "unknown" | "not_applicable";
            /** @description 企业实际值。 */
            enterpriseValue?: string | null;
            /** @description 政策要求值。 */
            policyValue?: string | null;
            /**
             * Format: double
             * @description 权重。
             */
            scoreWeight?: number | null;
            /**
             * Format: double
             * @description 得分。
             */
            scoreObtained?: number | null;
            /** @description 数据来源。 */
            dataSource?: string | null;
            /**
             * Format: int64
             * @description 数据时间，epoch 毫秒。
             */
            dataTime?: number | null;
            /** @description 判定原因。 */
            reason?: string | null;
            /**
             * Format: int64
             * @description 创建时间，epoch 毫秒。
             */
            createdAt?: number | null;
            /** @description 内部字段名，不展示。 */
            fieldName?: string | null;
            /** @description 比较运算符。 */
            compare?: string | null;
            /** @description 指标名称（业务文案）。 */
            indicator?: string | null;
        };
        /** @description AI 交互日志（补充接口，对接文档未列入前端必接）。 */
        AiInteractionLogRequest: {
            sessionId?: string | null;
            pageType?: string | null;
            /** Format: int64 */
            policyId?: number | null;
            entUid?: string | null;
            questionCategory?: string | null;
            resultStatus?: string | null;
        };
        BooleanResponse: components["schemas"]["ApiResponseEnvelope"] & {
            data?: boolean | null;
        };
    };
    responses: never;
    parameters: {
        /** @description MCP server 到 Java 的服务间调用凭证（仅服务间使用，浏览器/前端不携带）。本期前端联调阶段免鉴权，前端调用无需此头。 */
        PolicyCopilotServiceTokenHeader: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getDashboardSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 概览数据。业务失败时 `code=500`、`data=null`。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummaryResponse"];
                };
            };
        };
    };
    searchEnterprises: {
        parameters: {
            query: {
                /**
                 * @description 企业名称或统一社会信用代码（关键词）。
                 * @example 某科技有限公司
                 */
                query: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 企业候选列表。`query` 为空时 `code=500`。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnterpriseSearchResponse"];
                };
            };
        };
    };
    searchPolicies: {
        parameters: {
            query: {
                /**
                 * @description 政策名称或简称。
                 * @example 节能改造
                 */
                query: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 政策候选列表。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicySearchResponse"];
                };
            };
        };
    };
    searchProjects: {
        parameters: {
            query: {
                /**
                 * @description 限定政策名称或政策 ID。
                 * @example 节能改造补贴
                 */
                policyQuery?: string;
                /**
                 * @description 项目名称或项目 ID。
                 * @example 节能改造项目
                 */
                query: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 项目候选列表。`query` 为空时 `code=500`。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSearchResponse"];
                };
            };
        };
    };
    resolveMatches: {
        parameters: {
            query?: {
                /** @description matchId 或综合关键词。 */
                query?: string;
                /** @description 企业名称或统一社会信用代码。 */
                enterpriseQuery?: string;
                /** @description 政策名称或政策 ID。 */
                policyQuery?: string;
                /** @description 项目名称或项目 ID。 */
                projectQuery?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 匹配对象候选列表。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResolveResponse"];
                };
            };
        };
    };
    getEnterpriseContext: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 企业标识（`entUid`，对接文档中称 `enterpriseId`）。
                 * @example 10583BAEC594416585810EE1BF62514A
                 */
                entUid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 企业政策画像。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnterprisePolicyContextResponse"];
                };
            };
        };
    };
    getPolicyContext: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 政策 ID。
                 * @example 12
                 */
                policyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 政策上下文。政策不存在时 `code=500`、`msg="政策不存在"`、`data=null`。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyMatchContextResponse"];
                };
            };
        };
    };
    findPoliciesByEnterprise: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindPoliciesForEnterpriseRequest"];
            };
        };
        responses: {
            /** @description 匹配结果列表。空结果时 `items=[]` 且 `message="暂无匹配结果，请确认企业画像数据是否存在"`。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchListResponse"];
                };
            };
        };
    };
    findEnterprisesByPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindEnterprisesForPolicyRequest"];
            };
        };
        responses: {
            /** @description 匹配结果列表。`policyId` 为空时 `code=500`；空结果时 `items=[]` 且 `message` 给出空态文案。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchListResponse"];
                };
            };
        };
    };
    summarizeEnterprisesByPolicy: {
        parameters: {
            query: {
                /**
                 * @description 政策 ID。
                 * @example 12
                 */
                policyId: number;
                /**
                 * @description 项目 ID；不传时统计该政策下全部项目。
                 * @example 4
                 */
                projectId?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 匹配企业统计。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyEnterpriseMatchSummaryResponse"];
                };
            };
        };
    };
    getMatchEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 匹配结果标识。
                 * @example match_xxx
                 */
                matchId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 条件证据列表。`matchId` 不存在时 `code=500`、`msg="MATCH_NOT_FOUND"`。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchEvidenceResponse"];
                };
            };
        };
    };
    getMatchGaps: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 匹配结果标识。
                 * @example match_xxx
                 */
                matchId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 差距与材料提示。`matchId` 不存在时 `code=500`、`msg="MATCH_NOT_FOUND"`。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchGapsResponse"];
                };
            };
        };
    };
    logAiInteraction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiInteractionLogRequest"];
            };
        };
        responses: {
            /** @description 是否写入成功。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BooleanResponse"];
                };
            };
        };
    };
}
