/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/policy-copilot/v1/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 服务工作台总览
         * @description 返回 KPI、热门政策和企业找政策看板列表。topEnterprises 包含企业名称、所属节点和高匹配政策数。
         */
        get: operations["getDashboardSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policy-copilot/v1/analysis/park-policy-match-rate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 园区政策覆盖度
         * @description 返回全园区和上游/中游/下游政策覆盖度。matchRate 为 0~1 小数，前端乘 100 展示百分比。
         */
        get: operations["getParkPolicyMatchRate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policy-copilot/v1/enterprises/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 搜索企业 */
        get: operations["searchEnterprises"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policy-copilot/v1/policies/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 搜索政策 */
        get: operations["searchPolicies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policy-copilot/v1/projects/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 搜索政策项目 */
        get: operations["searchProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policy-copilot/v1/matches/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 解析匹配结果
         * @description 可通过 matchId、政策关键词、企业关键词和项目关键词定位匹配结果。
         */
        get: operations["resolveMatches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policy-copilot/v1/enterprises/{entUid}/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 企业画像上下文
         * @description 返回企业基础信息、指标画像、可展示画像项和缺失项。ent_reg_status 按 financial_ent_basic_indicator 取值。
         */
        get: operations["getEnterpriseContext"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policy-copilot/v1/policies/{policyId}/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 政策匹配上下文
         * @description 返回政策基础信息、项目和项目下条件。条件按 project_id + policy_id 交集取得。
         */
        get: operations["getPolicyContext"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policy-copilot/v1/matches/policies-by-enterprise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 企业找政策
         * @description 按企业实时执行当前政策范围内的匹配，并返回政策-项目匹配结果。
         */
        post: operations["matchPoliciesByEnterprise"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policy-copilot/v1/matches/enterprises-by-policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 政策找企业列表
         * @description 分页查询某政策或政策项目下最新匹配企业结果。
         */
        post: operations["findEnterprisesByPolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policy-copilot/v1/matches/enterprises-by-policy/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 政策找企业统计
         * @description 返回高/中/低匹配企业数，企业数按 ent_uid 去重。
         */
        get: operations["getEnterprisesByPolicySummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policy-copilot/v1/matches/{matchId}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 匹配证据明细 */
        get: operations["getMatchEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policy-copilot/v1/matches/{matchId}/gaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 匹配缺口诊断 */
        get: operations["getMatchGaps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policy-copilot/v1/ai-interactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 保存 AI 交互日志 */
        post: operations["saveAiInteraction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BaseResponse: {
            /** @example 200 */
            code: number;
            /** @example 操作成功 */
            msg: string;
            data?: unknown;
        };
        DashboardSummaryResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["DashboardSummary"];
        };
        DashboardSummary: {
            /** @example 1.0 */
            schemaVersion?: string;
            kpis?: components["schemas"]["DashboardKpis"];
            news?: Record<string, never>[];
            topPolicies?: components["schemas"]["TopPolicy"][];
            topEnterprises?: components["schemas"]["TopEnterprise"][];
        };
        DashboardKpis: {
            activePolicyCount?: number;
            servedEnterpriseCount?: number;
            matchAnalysisCount?: number;
        };
        TopPolicy: {
            /** Format: int64 */
            policyId?: number;
            title?: string;
            policyAttribute?: string;
            /** Format: date-time */
            deadline?: string | null;
            /**
             * Format: int64
             * @description 最新匹配结果下去重企业数
             */
            matchedEnterpriseCount?: number;
        };
        TopEnterprise: {
            entUid?: string;
            entName?: string;
            /** @description 所属产业链节点，多个节点用顿号分隔 */
            nodeName?: string | null;
            /**
             * Format: int64
             * @description 高匹配政策数，is_latest=1 且 match_level=high 的去重政策数
             */
            matchedPolicyCount?: number;
            maxScore?: number;
        };
        ParkPolicyMatchRateResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["ParkPolicyMatchRate"];
        };
        ParkPolicyMatchRate: {
            /** @example 1.0 */
            schemaVersion?: string;
            overall?: components["schemas"]["MatchRateStat"];
            segments?: components["schemas"]["MatchRateStat"][];
        };
        MatchRateStat: {
            /** @enum {string|null} */
            chainPosition?: "上游" | "中游" | "下游" | null;
            /** Format: int64 */
            totalCount?: number;
            /** Format: int64 */
            matchedCount?: number;
            /**
             * Format: double
             * @description 0~1 小数
             */
            matchRate?: number;
        };
        EnterpriseSearchResponse: components["schemas"]["BaseResponse"] & {
            data?: {
                items?: components["schemas"]["EnterpriseSearchItem"][];
            };
        };
        EnterpriseSearchItem: {
            enterpriseId?: string;
            enterpriseName?: string;
            creditCode?: string | null;
        };
        PolicySearchResponse: components["schemas"]["BaseResponse"] & {
            data?: {
                items?: components["schemas"]["PolicySearchItem"][];
            };
        };
        PolicySearchItem: {
            /** Format: int64 */
            policyId?: number;
            policyName?: string;
            policyFullName?: string | null;
        };
        ProjectSearchResponse: components["schemas"]["BaseResponse"] & {
            data?: {
                items?: components["schemas"]["ProjectSearchItem"][];
            };
        };
        ProjectSearchItem: {
            /** Format: int64 */
            policyId?: number;
            policyName?: string;
            /** Format: int64 */
            projectId?: number;
            projectName?: string;
        };
        MatchResolveResponse: components["schemas"]["BaseResponse"] & {
            data?: {
                items?: components["schemas"]["MatchResolveItem"][];
            };
        };
        MatchResolveItem: {
            matchId?: string;
            /** Format: int64 */
            policyId?: number;
            policyName?: string;
            /** Format: int64 */
            projectId?: number;
            projectName?: string;
            enterpriseId?: string;
            enterpriseName?: string;
            score?: number;
            matchLevel?: components["schemas"]["MatchLevel"];
        };
        EnterpriseContextResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["EnterpriseContext"];
        };
        EnterpriseContext: {
            schemaVersion?: string;
            entUid?: string;
            entName?: string;
            creditCode?: string | null;
            province?: string | null;
            city?: string | null;
            industryCategory?: string | null;
            registeredCapital?: string | null;
            enterpriseScale?: string | null;
            serviceProfile?: Record<string, never> | null;
            indicators?: components["schemas"]["EnterpriseIndicatorValue"][];
            profileItems?: components["schemas"]["ProfileItem"][];
            missingFields?: string[];
            missingDataItems?: string[];
            abnormalFields?: string[];
        };
        EnterpriseIndicatorValue: {
            fieldName?: string;
            fieldValue?: string | null;
            valueType?: string | null;
            unit?: string | null;
            sourceType?: string | null;
            sourceRef?: string | null;
            verifiedStatus?: string | null;
            /** Format: date-time */
            updatedAt?: string | null;
        };
        ProfileItem: {
            name?: string;
            value?: string | null;
            unit?: string | null;
            status?: string;
            source?: string;
            /** Format: date-time */
            updatedAt?: string | null;
        };
        PolicyContextResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["PolicyContext"];
        };
        PolicyContext: {
            schemaVersion?: string;
            /** Format: int64 */
            policyId?: number;
            title?: string;
            titleFull?: string | null;
            documentNo?: string | null;
            issuingOrg?: string | null;
            region?: string | null;
            level?: string | null;
            policyAttribute?: string | null;
            /** Format: date-time */
            deadline?: string | null;
            materials?: string | null;
            process?: string | null;
            projects?: components["schemas"]["PolicyProjectContext"][];
        };
        PolicyProjectContext: {
            /** Format: int64 */
            projectId?: number;
            projectName?: string;
            subjectType?: string | null;
            groupsRelation?: string | null;
            conditions?: components["schemas"]["PolicyCondition"][];
        };
        PolicyCondition: {
            /** Format: int64 */
            indicatorId?: number;
            indicator?: string;
            fieldName?: string;
            compare?: string;
            fieldVal?: string | null;
            conditionRole?: string | null;
            indicatorScore?: number | null;
            sourceClause?: string | null;
            matchStatus?: string | null;
        };
        FindPoliciesForEnterpriseReq: {
            entUid?: string;
            /** @description 兼容字段，和 entUid 二选一 */
            enterpriseId?: string;
            entName?: string;
            creditCode?: string;
            /** @description 当前实时匹配路径未使用，保留兼容 */
            policyAttribute?: string;
            /** @description 当前实时匹配路径未使用，保留兼容 */
            matchLevels?: components["schemas"]["MatchLevel"][];
            sort?: string;
            pageNum?: number;
            pageSize?: number;
        };
        FindEnterprisesForPolicyReq: {
            /** Format: int64 */
            policyId: number;
            /** Format: int64 */
            projectId?: number | null;
            /** @description 企业名称关键词 */
            keyword?: string;
            matchLevels?: components["schemas"]["MatchLevel"][];
            /** @default 1 */
            pageNum: number;
            /** @default 20 */
            pageSize: number;
        };
        MatchListResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["MatchList"];
        };
        MatchList: {
            schemaVersion?: string;
            analysisId?: string | null;
            items?: components["schemas"]["MatchItem"][];
            /** Format: int64 */
            total?: number | null;
            pageNum?: number | null;
            pageSize?: number | null;
            pages?: number | null;
            hasNext?: boolean | null;
            message?: string | null;
        };
        MatchItem: {
            matchId?: string;
            /** Format: int64 */
            policyId?: number;
            /** Format: int64 */
            projectId?: number;
            policyTitle?: string;
            projectName?: string;
            entUid?: string;
            entName?: string | null;
            score?: number;
            matchLevel?: components["schemas"]["MatchLevel"];
            eligibilityStatus?: string;
            confidence?: number;
            satisfiedCount?: number | null;
            unsatisfiedCount?: number | null;
            unknownCount?: number | null;
            notApplicableCount?: number | null;
            mainEvidenceSummary?: string[];
        };
        PolicyEnterpriseMatchSummaryResponse: components["schemas"]["BaseResponse"] & {
            data?: components["schemas"]["PolicyEnterpriseMatchSummary"];
        };
        PolicyEnterpriseMatchSummary: {
            schemaVersion?: string;
            /**
             * Format: int64
             * @description 高/中/低匹配去重企业数之和
             */
            total?: number;
            /** Format: int64 */
            highCount?: number;
            /** Format: int64 */
            mediumCount?: number;
            /** Format: int64 */
            lowCount?: number;
        };
        MatchEvidenceResponse: components["schemas"]["BaseResponse"] & {
            data?: {
                schemaVersion?: string;
                matchId?: string;
                items?: components["schemas"]["PolicyMatchEvidence"][];
            };
        };
        MatchGapsResponse: components["schemas"]["BaseResponse"] & {
            data?: {
                schemaVersion?: string;
                matchId?: string;
                missingData?: components["schemas"]["PolicyMatchEvidence"][];
                unsatisfied?: components["schemas"]["PolicyMatchEvidence"][];
                materials?: string[];
            };
        };
        PolicyMatchEvidence: {
            /** Format: int64 */
            id?: number;
            matchId?: string;
            /** Format: int64 */
            indicatorId?: number;
            /** @enum {string} */
            evidenceStatus?: "satisfied" | "unsatisfied" | "unknown" | "not_applicable";
            enterpriseValue?: string | null;
            policyValue?: string | null;
            scoreWeight?: number;
            scoreObtained?: number;
            dataSource?: string | null;
            /** Format: date-time */
            dataTime?: string | null;
            reason?: string | null;
            /** Format: date-time */
            createdAt?: string | null;
            fieldName?: string | null;
            compare?: string | null;
            indicator?: string | null;
        };
        AiInteractionLogReq: {
            sessionId?: string;
            pageType?: string;
            /** Format: int64 */
            policyId?: number;
            entUid?: string;
            questionCategory?: string;
            resultStatus?: string;
        };
        BooleanResponse: components["schemas"]["BaseResponse"] & {
            data?: boolean;
        };
        /** @enum {string} */
        MatchLevel: "high" | "medium" | "low" | "none";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getDashboardSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummaryResponse"];
                };
            };
        };
    };
    getParkPolicyMatchRate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParkPolicyMatchRateResponse"];
                };
            };
        };
    };
    searchEnterprises: {
        parameters: {
            query: {
                /** @description 企业名称或统一社会信用代码 */
                query: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnterpriseSearchResponse"];
                };
            };
        };
    };
    searchPolicies: {
        parameters: {
            query: {
                /** @description 政策名称或政策 ID */
                query: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicySearchResponse"];
                };
            };
        };
    };
    searchProjects: {
        parameters: {
            query: {
                /** @description 政策名称或政策 ID，可选 */
                policyQuery?: string;
                /** @description 项目名称或项目 ID */
                query: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSearchResponse"];
                };
            };
        };
    };
    resolveMatches: {
        parameters: {
            query?: {
                query?: string;
                enterpriseQuery?: string;
                policyQuery?: string;
                projectQuery?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResolveResponse"];
                };
            };
        };
    };
    getEnterpriseContext: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 企业唯一标识 */
                entUid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnterpriseContextResponse"];
                };
            };
        };
    };
    getPolicyContext: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 政策 ID */
                policyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyContextResponse"];
                };
            };
        };
    };
    matchPoliciesByEnterprise: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindPoliciesForEnterpriseReq"];
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchListResponse"];
                };
            };
        };
    };
    findEnterprisesByPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindEnterprisesForPolicyReq"];
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchListResponse"];
                };
            };
        };
    };
    getEnterprisesByPolicySummary: {
        parameters: {
            query: {
                policyId: number;
                projectId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyEnterpriseMatchSummaryResponse"];
                };
            };
        };
    };
    getMatchEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matchId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchEvidenceResponse"];
                };
            };
        };
    };
    getMatchGaps: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matchId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchGapsResponse"];
                };
            };
        };
    };
    saveAiInteraction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AiInteractionLogReq"];
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BooleanResponse"];
                };
            };
        };
    };
}
